### PR TITLE
[ci] add appveyor.yml

### PR DESCRIPTION
**Pull request by matlo607**
I would like to add a CI that would help you get a clear status before validating pull requests without having to do it yourself on your machine.
I created an account on [AppVeyor](https://ci.appveyor.com/) using my github account.
You can see on [this page](https://ci.appveyor.com/project/matlo607/stackwalker/build/add-ci-appveyor-ci-4) a sum up of 3 builds (Visual Studio 2013, 2015 and 2017).
I noticed I introduced a regression with the last pull request for clang-format.
```
 C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\CL.exe /c /IC:\projects\stackwalker\Main\StackWalker /I"C:\Tools\vcpkg\installed\x64-windows\include" /Zi /nologo /W4 /WX- /diagnostics:classic /O2 /Ob1 /D WIN32 /D _WINDOWS /D _SECURE_SCL=0 /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_DEPRECATE /D NDEBUG /D "CMAKE_INTDIR=\"RelWithDebInfo\"" /D _MBCS /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"StackWalker.dir\RelWithDebInfo\\" /Fd"StackWalker.dir\RelWithDebInfo\StackWalker.pdb" /Gd /TP /FC /errorReport:queue C:\projects\stackwalker\Main\StackWalker\StackWalker.cpp
  StackWalker.cpp
c:\projects\stackwalker\main\stackwalker\stackwalker.h(232): warning C4010: single-line comment contains line-continuation character [C:\projects\stackwalker\build-dir\StackWalker.vcxproj]
c:\projects\stackwalker\main\stackwalker\stackwalker.h(233): warning C4010: single-line comment contains line-continuation character [C:\projects\stackwalker\build-dir\StackWalker.vcxproj]
c:\projects\stackwalker\main\stackwalker\stackwalker.h(234): warning C4010: single-line comment contains line-continuation character [C:\projects\stackwalker\build-dir\StackWalker.vcxproj]
c:\projects\stackwalker\main\stackwalker\stackwalker.h(235): warning C4010: single-line comment contains line-continuation character [C:\projects\stackwalker\build-dir\StackWalker.vcxproj]
c:\projects\stackwalker\main\stackwalker\stackwalker.h(236): warning C4010: single-line comment contains line-continuation character [C:\projects\stackwalker\build-dir\StackWalker.vcxproj]
c:\projects\stackwalker\main\stackwalker\stackwalker.h(237): warning C4010: single-line comment contains line-continuation character [C:\projects\stackwalker\build-dir\StackWalker.vcxproj]
c:\projects\stackwalker\main\stackwalker\stackwalker.h(238): warning C4010: single-line comment contains line-continuation character [C:\projects\stackwalker\build-dir\StackWalker.vcxproj]
c:\projects\stackwalker\main\stackwalker\stackwalker.h(240): warning C4010: single-line comment contains line-continuation character [C:\projects\stackwalker\build-dir\StackWalker.vcxproj]
```
Full logs are available on [this page](https://ci.appveyor.com/project/matlo607/stackwalker/build/add-ci-appveyor-ci-4/job/ropncav9fxeu0w8l).
It looks a lot like travis-ci.
Do you mind creating an account on [AppVeyor](https://ci.appveyor.com/) and register your project on it?

### CODE REVIEW

**Review by JochenKalmbach — DISMISSED** [review]
Why is the file "appveyor.yml" not placed in "Main/Stackwalker"? Is this not possible?

**Comment by JochenKalmbach** [comment]
We can also discuss if we rename the "Main/Stackwalker" to "src"...

**Comment by JochenKalmbach** [comment]
Do you know how to configure the AppVeyor correctly?

**Comment by JochenKalmbach** [comment]
AppVoyer added hopefully correct…

**Comment by matlo607** [comment]
From what I discovered yesterday when I configured it on my fork, you just have to tell to track all the branches on this repository with a appveyor.yml, the file content will do the remaining configuration for you.

**Comment by JochenKalmbach** [comment]
Yes thanks! I merged it and build works....

**Comment by matlo607** [comment]
> We can also discuss if we rename the "Main/Stackwalker" to "src"...

Yes, I agree. What do you think about :
* splitting main.cpp in several tests and move the files in tests/
* running these tests in AppVeyor
* question: how to handle one of the test opening a pop up ?
* moving StackWalker.h in /include and StackWalker.cpp in /src

**Pull request merged**
