### PR TITLE
Windows ARM64 support

### PR DESCRIPTION
**Pull request by ZacWalk**
This PR adds Windows on ARM64 support. 

The code changes are based on the approach Chromium took. I have run tests on my Surface ProX (ARM64 machine) and everything looked good. I also created VS2022 project files for testing.

### CODE REVIEW

**Comment by equalman** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by JochenKalmbach** [comment]
Thanks for your PR!
Can you add the environment to the appveyor build pipeline?
==> https://github.com/JochenKalmbach/StackWalker/blob/master/appveyor.yml

**Comment by ZacWalk** [comment]
@JochenKalmbach how does that look? Took a few attempts but I got VS 2022 building it for ARM64 on appveyor.

**Comment by ZacWalk** [comment]
Thanks Jochen (y)

**Pull request merged**
